spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web?characterEncoding=utf8
    username: root
    password: ZhouLian19990926
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml