spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web?characterEncoding=utf8
    username: root
    password: ZhouLian19990926
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
  web:
    resources:
      static-locations: file:D://test/



mybatis:
  mapper-locations: classpath:mapper/*.xml
